# Generated by Django 4.2.7 on 2024-01-12 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entertainment', '0002_entertainmentmaterial_description_and_more'),
        ('learning_tracker', '0001_initial'),
        ('sessions_manager', '0004_remove_project_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('reward_text', models.TextField(blank=True, null=True)),
                ('learning_materials', models.ManyToManyField(blank=True, null=True, to='learning_tracker.material')),
                ('projects', models.ManyToManyField(blank=True, null=True, to='sessions_manager.project')),
                ('rewards', models.ManyToManyField(to='entertainment.entertainmentmaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
