# Generated by Django 4.2.7 on 2024-01-12 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.taskscontainer'),
        ),
    ]
