# Generated by Django 4.2.7 on 2024-01-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_container'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskscontainer',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
