# Generated by Django 4.2.7 on 2024-02-16 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskscontainer_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskscontainer',
            name='reminder',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
