# Generated by Django 4.2.7 on 2023-11-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0002_alter_project_finish_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.CharField(choices=[('in progress', 'in_progress'), ('completed', 'completed')], default='in progress', max_length=50),
        ),
    ]
