# Generated by Django 4.2.7 on 2023-11-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_manager', '0003_alter_project_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
    ]
