# Generated by Django 4.2.7 on 2024-07-18 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntertainmentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField()),
                ('image', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('anime', 'anime'), ('game', 'game'), ('shows & movies', 'shows & movies'), ('other', 'other')], max_length=15)),
                ('status', models.CharField(choices=[('current', 'current'), ('done', 'done'), ('later', 'later')], default='current', max_length=15)),
                ('special', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
