# Generated by Django 4.2.7 on 2024-01-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainmentmaterial',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entertainmentmaterial',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
