# Generated by Django 4.2.7 on 2024-02-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0002_entertainmentmaterial_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainmentmaterial',
            name='type',
            field=models.CharField(choices=[('anime', 'anime'), ('game', 'game'), ('other', 'other')], max_length=15),
        ),
    ]
