# Generated by Django 4.2.7 on 2024-03-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entertainment', '0003_alter_entertainmentmaterial_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entertainmentmaterial',
            name='type',
            field=models.CharField(choices=[('anime', 'anime'), ('game', 'game'), ('shows & movies', 'shows & movies'), ('other', 'other')], max_length=15),
        ),
    ]
